export const defaultScaleOptions = [
  { value: 1.067, label: 'Minor Second' },
  { value: 1.125, label: 'Major Second' },
  { value: 1.2, label: 'Minor Third' },
  { value: 1.25, label: 'Major Third' },
  { value: 1.333, label: 'Perfect Fourth' },
  { value: 1.414, label: 'Augmented Fourth' },
  { value: 1.5, label: 'Perfect Fifth' },
  { value: 1.618, label: 'Golden Ratio' },
];

export function getScaleByValue(value) {
  return { ...defaultScaleOptions.find((opt) => opt.value == value) };
}

export const defaultMediaQueries = {
  labels: ['s', 'm', 'l', 'xl', 'xxl'],
  minWidths: ['', '45rem', '60rem', '90rem', '120rem'],
  scales: [
    defaultScaleOptions[1],
    defaultScaleOptions[2],
    defaultScaleOptions[4],
    defaultScaleOptions[5],
    defaultScaleOptions[6],
  ],
};

export function getInitialMediaQueries() {
  const mqs = [];

  for (let i = 0; i < 3; i++) {
    mqs.push({
      label: defaultMediaQueries.labels[i],
      minWidth: defaultMediaQueries.minWidths[i],
      scale: defaultMediaQueries.scales[i],
      id: i,
    });
  }

  return mqs;
}

export function generateFontSizeByScale(scale, step, as_rem = true) {
  let font_size = 1;

  for (let i = 0; i < step; i++) {
    font_size = font_size * scale;
  }

  font_size = Math.round(font_size * 1000) / 1000;

  if (as_rem) {
    return `${font_size}rem`;
  }
  return font_size;
}

export function generateClampedFontSize(
  lower_scale,
  upper_scale,
  scalingType,
  step
) {
  const lower_value = generateFontSizeByScale(lower_scale, step, false);
  const upper_value = generateFontSizeByScale(upper_scale, step, false);

  // TODO:  This can be simplified. The / 2 / 50 is undone by the * 100
  // NOTE:  leaving this in, as possible the 50 (based on a 50rem width screen)
  //        may be something to be made customizable

  const screen_base_size = 50; // based on 50rem width screen

  const scaling_value =
    Math.round(
      ((lower_value + upper_value) / 2 / screen_base_size) * 100 * 1000
    ) / 1000;

  return `clamp(${lower_value}rem, ${scaling_value}${scalingType}, ${upper_value}rem)`;
}

export const defaultHeadings = [
  {
    tag: 'h1',
    step: 6,
    style: {
      lineHeight: 1.1,
    },
  },
  {
    tag: 'h2',
    step: 5,
    style: {
      lineHeight: 1.2,
    },
  },
  {
    tag: 'h3',
    step: 4,
    style: {
      lineHeight: 1.3,
    },
  },
  {
    tag: 'h4',
    step: 3,
  },
  {
    tag: 'h5',
    step: 2,
  },
  {
    tag: 'h6',
    step: 1,
  },
];

const generatedStylesStart =
  '/* ---------- Start of typography code generated by responsivetype.ca ---------- */';
const generatedStylesEnd =
  '/* ---------- End of typography code generated by responsivetype.ca ---------- */';

export function generateRuleSetArray(
  extraSteps,
  includeH6,
  lowerScale,
  upperScale,
  scalingType
) {
  const classNameBase = '.type-scale-';
  const startingNum = includeH6 ? 6 : 5;

  // Create rule sets data
  const ruleSets = [];

  // if not including h6 in scales, add basic h6 ruleset
  if (!includeH6) {
    ruleSets.push({
      selectors: ['h6', `${classNameBase}h6`],
      rules: [['font-size', '1rem']],
    });
  }

  // loop through base headings and extra steps
  for (let i = 0; i < startingNum + extraSteps; i++) {
    const selectors = [];
    const rules = [];

    // set up selectors

    // base selector label
    let label = `h${startingNum - i}`;

    if (startingNum - i > 0) {
      // Base headings route

      // add heading element selector
      selectors.push(`h${startingNum - i}`);
    } else {
      // Extra scales route

      // generate class name for extra steps
      const amount = includeH6 ? i - 5 : i - 4;

      label = '';

      // for each step above basic headings, add an extra `x`
      for (let i = 0; i < amount; i++) {
        label = `${label}x`;
      }

      // complete `xl` like label
      label = `${label}l`;
    }

    // add classname selector
    selectors.push(`${classNameBase}${label}`);

    // add rules if necessary styles are provided
    if (lowerScale && upperScale && scalingType) {
      // Generate clamped font size and push to rules
      rules.push([
        `font-size`,
        generateClampedFontSize(lowerScale, upperScale, scalingType, i + 1),
      ]);
    }

    // push
    ruleSets.push({
      selectors,
      rules,
      step: i + 1,
    });
  }

  const reorderedRuleSets = [...ruleSets].reverse();

  console.log(reorderedRuleSets);

  return reorderedRuleSets;
}

export function convertRuleSetArrayToString(rulesets, asVariables) {
  let cssString = ``;

  rulesets.forEach(({ selectors, rules }) => {
    const rulesAsString = [];

    if (rules.length) {
      rules.forEach((r) => {
        if (asVariables && r[0] === 'font-size') {
          const variableName = selectors
            .filter((s) => s.includes('type-scale'))[0]
            .replace('.', '--');

          rulesAsString.push(`font-size: var(${variableName});`);
        } else {
          rulesAsString.push(`${r.join(': ')};`);
        }
      });
    } else {
      const variableName = selectors
        .filter((s) => s.includes('type-scale'))[0]
        .replace('.', '--');
      rulesAsString.push(`font-size: var(${variableName});`);
    }
    // add selectors to rule set code
    let rsString = selectors.join(', \n');

    // add rules to rule set code
    rsString =
      rsString +
      ` {
  ${rulesAsString.join(`\n  `)}
}`;

    cssString =
      cssString +
      `${rsString}

`;
  });

  return cssString;
}

export function generateClampVariables(rulesets) {
  const variablesAsArray = [];

  rulesets.forEach(({ selectors, rules }) => {
    // get type scale label from selectors
    const variableName = selectors
      .filter((s) => s.includes('type-scale'))[0]
      .replace('.', '--');

    // get font size rule
    const fontSize = rules.filter((r) => r.includes('font-size'))[0][1];
    // get font size value

    // combine label as variable name with font-size value
    variablesAsArray.push(`${variableName}: ${fontSize};`);
  });

  return variablesAsArray.join(`\n  `);
}

export function generateMQVariables(mediaQueries, stepsAsArray) {
  let cssString = '';
  // loop through media queries
  mediaQueries.forEach(({ label, minWidth, scale }, i) => {
    let indent = '  ';
    // Label MQ
    cssString =
      cssString +
      `\n\n  /* ----- ${label.toUpperCase()} | scale: ${scale.value} - ${
        scale.label
      } ----- */`;
    if (i > 0) {
      // if not first loop, add appropriate @media
      cssString =
        cssString + `\n  @media only screen and (min-width: ${minWidth}) {`;

      // increase indent for within the @media
      indent = '    ';
    }

    // loop through stepsAsArray
    stepsAsArray.forEach(({ selectors, step }) => {
      // get type scale label from selectors

      // set variable name
      const variableName = selectors
        .filter((s) => s.includes('type-scale'))[0]
        .replace('.', '--');

      // set variable value
      const fontSize = generateFontSizeByScale(scale.value, step);

      // append string
      cssString = cssString + `\n${indent}${variableName}: ${fontSize};`;
    });

    if (i > 0) {
      // if not first loop, add closing }
      cssString = cssString + `\n  }`;
    }
  });

  return cssString;
}

export function generateClampStyles(
  lowerScale,
  upperScale,
  scalingType,
  includeH6,
  extraSteps,
  asVariables
) {
  const ruleSetsArray = generateRuleSetArray(
    extraSteps,
    includeH6,
    lowerScale,
    upperScale,
    scalingType
  );

  let cssString = generatedStylesStart;

  if (asVariables) {
    const variablesString = generateClampVariables(ruleSetsArray);

    cssString =
      cssString +
      `\n\n:root {
  /* Type Scales */
  ${variablesString}
}`;
  }

  // convert rule sets array array to css string
  cssString =
    cssString +
    `\n\n${convertRuleSetArrayToString(ruleSetsArray, asVariables)}`;

  cssString = cssString + generatedStylesEnd;

  return cssString;
}

export function generateMQStyles(
  mediaQueries,
  includeH6,
  extraSteps,
  asVariables
) {
  let cssString = generatedStylesStart;

  const ruleSetsArray = generateRuleSetArray(extraSteps, includeH6);
  // create a similar set up as convertRuleSetArrayToString for the steps

  if (asVariables) {
    // if asVariables loop through mqs in :root
    cssString =
      cssString +
      `\n\n:root {
  /* Type Scales */${generateMQVariables(mediaQueries, ruleSetsArray)}

}

${convertRuleSetArrayToString(ruleSetsArray, asVariables)}`;

    // loop through each step and update scale variable per mqs in :root
    // apply variables to each step's selectors
  } else {
    mediaQueries.forEach(({ label, minWidth, scale }, i) => {
      let indent = '';

      // Label MQ
      cssString =
        cssString +
        `\n\n/* ----- ${label.toUpperCase()} | scale: ${scale.value} - ${
          scale.label
        } ----- */`;
      if (i > 0) {
        // if not first loop, add appropriate @media
        cssString =
          cssString + `\n@media only screen and (min-width: ${minWidth}) {`;

        // increase indent for within the @media
        indent = '  ';
      }

      // loop through stepsAsArray
      ruleSetsArray.forEach(({ selectors, step }) => {
        // add selectors
        cssString =
          cssString +
          `\n\n${indent}${selectors.join(`, \n${indent}`)} {
  ${indent}font-size: ${generateFontSizeByScale(scale.value, step)};
${indent}}`;
      });

      if (i > 0) {
        // if not first loop, add closing }
        cssString = cssString + `\n\n}`;
      }
    });

    cssString = cssString + '\n\n';
  }

  cssString = cssString + generatedStylesEnd;

  return cssString;
}

// export function generateStyles(
//   usingMediaQueries,
//   lowerScale,
//   upperScale,
//   scalingType,
//   mediaQueries
// ) {
//   let generatedStyles = `/* ---------- Start of typography code generated by responsivetype.ca ---------- */`;

//   if (usingMediaQueries) {
//     // Set mediaQueries headings

//     mediaQueries.forEach((mq, i) => {
//       // Generate all heading code at media query

//       let headingsCode = ``;

//       defaultHeadings.forEach((heading) => {
//         if (i > 0) {
//           headingsCode =
//             headingsCode +
//             `
//   ${heading.tag} {
//     font-size: ${generateFontSizeByScale(mq.scale.value, heading.step)};
//   }
//     `;
//         } else {
//           headingsCode =
//             headingsCode +
//             `
// ${heading.tag} {
//   font-size: ${generateFontSizeByScale(mq.scale.value, heading.step)};
// }
//     `;
//         }
//       });

//       // If not first item, include a media query
//       if (i > 0) {
//         generatedStyles =
//           generatedStyles +
//           `
// /* ----- ${mq.label.toUpperCase()} | scale: ${mq.scale.value} - ${
//             mq.scale.label
//           } ----- */

// @media only screen and (min-width: ${mq.minWidth}) {
//   ${headingsCode}
// }
// `;
//       } else {
//         generatedStyles =
//           generatedStyles +
//           `

// /* ----- ${mq.label.toUpperCase()} | scale: ${mq.scale.value} - ${
//             mq.scale.label
//           } ----- */
// ${headingsCode}
//           `;
//       }
//     });
//   } else {
//     // Set clamp headings
//     defaultHeadings.forEach((heading) => {
//       generatedStyles =
//         generatedStyles +
//         `

// ${heading.tag} {
//   font-size: ${generateClampedFontSize(
//     lowerScale,
//     upperScale,
//     scalingType,
//     heading.step
//   )};
// }
//   `;
//     });
//   }

//   generatedStyles =
//     generatedStyles +
//     `

// /* ---------- End of typography code generated by responsivetype.ca ---------- */
//     `;

//   return generatedStyles;
// }
